steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose:
        build: frontend
        image-repository: antic.website:5000/buildkiteci/frontend
    env:
      RAILS_ENV: test
    agents:
      queue: default
  - wait

  - name: ":eslint:"
    command: ".buildkite/eslint.sh"
    plugins:
      docker-compose#ed68516:
        run: frontend

  - name: ":jest:"
    command: ".buildkite/jest.sh"
    artifact_paths: "coverage/*"
    plugins:
      docker-compose#ed68516:
        run: frontend

  - name: ":webpack:"
    command: ".buildkite/webpack.sh"
    artifact_paths: "dist/*"
    plugins:
      docker-compose#ed68516:
        run: frontend

  - wait

  - name: ":rocket:"
    command: ".buildkite/deploy.sh"
    branches: "master"
    artifact_paths: "tmp/verify/*"
    agents:
      queue: "deploy"
